packages:
  - apps/*
  - packages/*
  - apps/mobileapp/electron

onlyBuiltDependencies:
  - core-js
  - cypress
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
