"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Footer = Footer;
const jsx_runtime_1 = require("react/jsx-runtime");
const Layouts_1 = require("../Layouts");
const Separator_1 = require("../Separator");
const Typography_1 = require("../Typography");
function Footer() {
    return ((0, jsx_runtime_1.jsxs)(Layouts_1.YStack, { className: "bg-background border-t border-slate-200 dark:border-slate-800 px-4 py-8 gap-4", children: [(0, jsx_runtime_1.jsxs)(Layouts_1.XStack, { className: "flex-wrap justify-between gap-4", children: [(0, jsx_runtime_1.jsxs)(Layouts_1.YStack, { className: "min-w-[200px] gap-2", children: [(0, jsx_runtime_1.jsx)(Typography_1.Text, { className: "text-lg font-bold", children: "Syncstuff" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { className: "text-slate-500 dark:text-slate-400", children: "Synchronize your files and clipboard across all your devices." })] }), (0, jsx_runtime_1.jsxs)(Layouts_1.XStack, { className: "flex-wrap gap-8", children: [(0, jsx_runtime_1.jsxs)(Layouts_1.YStack, { className: "gap-2", children: [(0, jsx_runtime_1.jsx)(Typography_1.Text, { className: "font-bold", children: "Product" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Features" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Downloads" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Premium" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Campaigns" })] }), (0, jsx_runtime_1.jsxs)(Layouts_1.YStack, { className: "gap-2", children: [(0, jsx_runtime_1.jsx)(Typography_1.Text, { className: "font-bold", children: "Company" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "About" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Blog" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "FAQ" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Contact" })] }), (0, jsx_runtime_1.jsxs)(Layouts_1.YStack, { className: "gap-2", children: [(0, jsx_runtime_1.jsx)(Typography_1.Text, { className: "font-bold", children: "Legal" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Privacy" }), (0, jsx_runtime_1.jsx)(Typography_1.Text, { children: "Terms" })] })] })] }), (0, jsx_runtime_1.jsx)(Separator_1.Separator, {}), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-row justify-between items-center", children: [(0, jsx_runtime_1.jsxs)(Typography_1.Text, { className: "text-sm text-slate-500 dark:text-slate-400", children: ["\u00A9 ", new Date().getFullYear(), " Involvex. All rights reserved."] }), (0, jsx_runtime_1.jsx)(Layouts_1.XStack, { className: "gap-4" })] })] }));
}
//# sourceMappingURL=Footer.js.map